### ISSUE TITLE
FireFox does not like keyboard shortcuts

### ISSUE THREAD

**Issue by wbconnor** [voraciousdev/octo#12]
So far FF on desktop has had trouble with all the keyboard shortcuts I've tried to use

- Actions Menu `cmd` + `k`
  - opens address bar
- New Note `cmd` + `k` + `n`
  - opens address bar and then new window
- Change Context `cmd` + `k` + `c`
  - opens address bar and then nothing

**Comment by voraciousdev** [comment]
@wbconnor can you add the OS (including version) as well as the FireFox version?

**Comment by wbconnor** [comment]
Mac Mojave 10.14.6
Firefox 79.0

**Comment by voraciousdev** [comment]
Looks like `cmd+k` is reserved for searching via the Firefox address bar. Eventually, I would love for users to be able to define shortcuts themselves. For now, I will look into preventing the default behavior. If that doesn't work, I might need to change the shortcut. 😕

**Comment by voraciousdev** [comment]
This change should have been shipped in the open source editor.
