### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by DeFUCC** [voraciousdev/octo#40]
Hello! The app is amazing! I love Vue and it's a luck to find octo. I have many ideas about collaborative project management and will be happy to participate somehow in the development. First thing, that I see from the start – light/dark theme selection is a need for note-taking different situations. ;) It's a matter of changing a body class with some css variables.

**Comment by voraciousdev** [comment]
Thank you so much! I'm happy you're liking it, and the good news is that a light theme is definitely on the roadmap. 😄  Quick toggling is a great idea, and I will happily add that once the light theme is done too.

**Comment by voraciousdev** [comment]
This relates to #10.

**Comment by adamcstephens** [comment]
Is the system setting available in browser? I've become a big fan of toggling light/dark in the system and most apps follow along. Would be great to have an option to use what the host system has applied.

**Comment by DeFUCC** [comment]
> Is the system setting available in browser? I've become a big fan of toggling light/dark in the system and most apps follow along. Would be great to have an option to use what the host system has applied.

Yes! And it's very easy to implement just with CSS. Here's a quote from one of my current projects:
```
@media (prefers-color-scheme: dark) {  
  :root {   
    --bg-light: #444;  
    --bg-gray: #555;   
    --darker-gray: #333;   
    --text-color:#eee;   
    --text-light-color: #ccc;  
  }  
}  
```

**Comment by voraciousdev** [comment]
@adamcstephens great idea! The first step will be building the light theme, but defaulting to the system settings sounds like a really nice user experience once both are available.
