### ISSUE TITLE
Add bottom padding to tag list

### ISSUE THREAD

**Issue by wbconnor** [voraciousdev/octo#45]
My very bottom tag (funny enough the most important tag, _work_) was hidden by the browsers URL preview popup.

This happened on Mac using Chrome (I don't think you need the version numbers for this one)

![Screen Shot 2020-09-22 at 5 37 07 PM](https://user-images.githubusercontent.com/8883983/93940481-86b12000-fcfa-11ea-9f18-37e85690143c.png)

**Comment by voraciousdev** [comment]
I believe this only happens when you're hovering over a link (like one of the other tags). If you try to hover over the bottom-left tag, it _should_ automatically move this bar out of the way (likely to the right side). Can you confirm that behavior?

**Comment by voraciousdev** [comment]
I guess I left the bottom padding change out after all. 😬

**Comment by Noplautikus** [comment]
Hi, i would like to work on this.
