### ISSUE TITLE
Keymapping unset after vim mode upgrade

### ISSUE THREAD

**Issue by isaacdomini** [voraciousdev/octo#78]
After updating the app (with the addition of vim mode), keymapping setting was unset in Editor Settings. This stopped me from being able to edit or create any documents.

Note possible reason: settings get stored and loaded from IndexedDB. My "old" settings probably just overwrote the defaults.

**Comment by voraciousdev** [comment]
Thanks for adding the details here! I'm going to label this as a bug, and I will get it fixed soon. Here is a temporary "solution" for those that run into this:

- Open 'Editor Settings'
- Select 'Default' under 'Keymaps'
