### ISSUE TITLE
Can't scroll in the settings pane on iOS

### ISSUE THREAD

**Issue by blinthicum** [voraciousdev/octo#87]
Works fine on desktop chrome using inspector (mobile phone), but can't scroll on my iPhone (safari/chrome/etc).

This is preventing me from enabling encryption... 😬

**Comment by blinthicum** [comment]
<img width="504" alt="Screen Shot 2020-12-23 at 2 42 56 PM" src="https://user-images.githubusercontent.com/3454714/103032204-7f81f400-452d-11eb-83f8-3b491fc65f49.png">

**Comment by voraciousdev** [comment]
I was able to reproduce this in BrowserStack, so I'll start working on a fix soon.

**Comment by voraciousdev** [comment]
From what I can tell by my testing in BrowserStack, all scrolling is broken on iOS. This appears to be due to the ResizeObserver polyfill included with `simplebar`.
https://github.com/Grsmto/simplebar/blob/1d576e61bd70d87c726e03b338f0f406a2424210/packages/simplebar/src/simplebar.js#L303
